# Use a imagem do Node.js como base para compilar o projeto Angular
FROM node:14 as builder

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo package.json e package-lock.json para instalar as dependências
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante dos arquivos da aplicação
COPY . .

# Compile a aplicação Angular
RUN npm run build --prod

# Agora, use uma imagem mais leve do Node.js para servir a aplicação Express
FROM node:14-alpine

# Defina o diretório de trabalho para a aplicação Express
WORKDIR /app

# Copie os arquivos necessários para a aplicação Express
COPY server.js package*.json ./

# Instale as dependências do servidor
RUN npm install --only=production

# Copie a pasta de build do Angular para a pasta de distribuição do servidor Express
COPY --from=builder /app/dist /app/public

# Exponha a porta em que o servidor Express vai rodar (pode ser a mesma porta que o Angular usa)
EXPOSE 3000

# Inicie o servidor Express
CMD ["node", "server.js"]
